use std::fs;
use std::io::{BufRead, BufReader};
use std::path::Path;

use crate::types::CheckResult;

fn check_if_license_is_present(path: &Path) -> CheckResult<bool> {
    if !path
        .extension()
        .map(|ex| ex == "rs" || ex == "m")
        .unwrap_or(false)
    {
        return Ok(true);
    }
    let f =
        fs::File::open(path).map_err(|e| format!("Failed to open `{}`: {}", path.display(), e))?;
    let f = BufReader::new(f);
    let header: Vec<String> = f.lines().take(2).map(|x| x.unwrap()).collect();
    if header.len() != 2 {
        println!("xx> Missing header in `{}`", path.display());
        Ok(false)
    } else if header[0] == "// This file was generated by gir (https://github.com/gtk-rs/gir)" {
        // File generated by gir, no need to check further in here.
        Ok(true)
    } else if header[0]
        != "// Take a look at the license at the top of the repository in the LICENSE file."
    {
        println!("xx> Missing header in `{}`", path.display());
        Ok(false)
    } else if !header[1].is_empty() {
        println!(
            "xx> Expected empty line after license header in `{}`",
            path.display()
        );
        Ok(false)
    } else {
        Ok(true)
    }
}

fn inner_license_check(folder: &Path) -> CheckResult<usize> {
    let mut nb_errors = 0;
    for entry in fs::read_dir(folder)
        .map_err(|e| format!("Failed to read directory `{}`: {}", folder.display(), e))?
    {
        let entry = entry.expect("Failed to enter directory");
        let path = entry.path();
        if !path.is_dir() {
            if !check_if_license_is_present(&path)? {
                nb_errors += 1;
            }
        } else {
            nb_errors += inner_license_check(&path)?;
        }
    }
    Ok(nb_errors)
}

pub fn run_check<P: AsRef<Path>>(folder: &P) -> CheckResult<bool> {
    let folder = folder.as_ref();
    let src_dir = folder.join("src");
    println!("==> Checking license headers from `{}`", src_dir.display());
    let nb_errors = inner_license_check(&src_dir)?;
    println!("<== done");
    Ok(nb_errors == 0)
}
